apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NCCL_TUNER_PLUGIN
          value: "none"
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: NCCL_NET_PLUGIN
          value: ""
  - target:
      kind: LeaderWorkerSet
    patch: |-
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: NCCL_TUNER_PLUGIN
          value: "none"
      - op: add
        path: /spec/leaderWorkerTemplate/workerTemplate/spec/containers/0/env/-
        value:
          name: NCCL_NET_PLUGIN
          value: ""
